---
title: "Analysis"
author: "Xiaoya Li"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(e1071)
library(class)

source("../code/utils.R")

```

```{r}
all <- read.csv("../data/all.csv")
featureList <- c("NDAI", "SD", "CORR", "DF", "CF", "BF", "AF", "AN")
```


### Split Using two method

```{r}
set.seed(9)
folds1 <- splitMethod1(all, 10)
folds2 <- splitMethod2(all, 10)

trainVal1 <- all[-folds1[[10]],]
val1 <- all[folds1[[9]],]
test1 <- all[folds1[[10]],]

trainVal2 <- all[-folds2[[10]],]
val2 <- all[folds2[[9]],]
test2 <- all[folds2[[10]],]
```

Trivial classifier accuracy:

```{r}
mean(val1$label == 0)
mean(test1$label == 0)

mean(val2$label == 0)
mean(test2$label == 0)
```

### KNN with cross validation

```{r}
set.seed(30)
cv_loss1 <- CVgeneric("KNN", splitMethod1, trainVal1, featureList, "label", 5, misclassification)
```

```{r}
cv_loss1
```

```{r}
knn_test_pred <- knn(train_val_feature, testset[,featureList], train_val_label, 5)
knn_test_error <- misclassification(testset[,"label"], knn_test_pred)
knn_test_error
```











